package com.marnone.ai_arena.application;

public enum SessionEventType {
	VALIDATION_STARTED,
	VALIDATION_ACCEPTED,
	VALIDATION_REJECTED,
	TEAM_PLANNED,
	EXPERT_CREATED,
	DEBATE_MESSAGE,
	SUPERVISOR_DECISION,
	JUDGEMENT,
	FINAL_ANSWER,
	ERROR
}
